version: '0.1'

services:
  pgsql:
    image: postgres:12.2
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: full_proj_db
      POSTGRES_USER: full_proj_db
      POSTGRES_DB: full_proj_db
    restart: always